# Generated by Django 4.2.3 on 2023-07-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0004_alter_departments_name_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
