# Generated by Django 4.2.3 on 2023-07-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0005_alter_courses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
