# Generated by Django 4.2.3 on 2023-08-01 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0006_rename_details_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='States',
        ),
        migrations.AddField(
            model_name='detail',
            name='address',
            field=models.TextField(default='nil', max_length=250),
        ),
        migrations.AddField(
            model_name='detail',
            name='age',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detail',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='gender',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='mail',
            field=models.EmailField(default='abc@abc.abc', max_length=254),
        ),
        migrations.AddField(
            model_name='detail',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=910000000000),
        ),
        migrations.AddField(
            model_name='detail',
            name='materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_store_app.materials'),
        ),
        migrations.AddField(
            model_name='detail',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_store_app.purpose'),
        ),
    ]
