# Generated by Django 4.2.3 on 2023-08-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0007_materials_purpose_delete_states_detail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=128),
        ),
    ]
