# Generated by Django 4.2.3 on 2023-08-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0012_alter_detail_gender_alter_detail_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='materials',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_store_app.materials'),
        ),
    ]
